=== vika95viktoria/EpamCourses/epamTask5/out/artifacts/epamTask5_war_exploded/WEB-INF/classes/data/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs" elementFormDefault="qualified">
    <element name="abstractTariff" type="tns:AbstractTariff" abstract="true"></element>
    <element name="tariff" type="tns:Tariff" substitutionGroup="tns:abstractTariff"></element>
    <element name="Tariffs">
        <complexType>
            <sequence>
                <element ref="tns:abstractTariff"
                         minOccurs="1"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="AbstractTariff">
    <sequence>
    <element name="payroll">
        <simpleType>
            <restriction base="nonNegativeInteger">
               <maxExclusive value="1000000"/>
            </restriction>
        </simpleType>
        </element>
    <element name="callprices" type="tns:callprices" />
    </sequence>
    </complexType>
    <complexType name="Tariff">
        <complexContent>
            <extension base="tns:AbstractTariff">
        <sequence>
            <element name="sms" type="tns:price"/>
            <element name="parameters" type="tns:parameters"/>
        </sequence>
        <attribute name="name" type="tns:tariffName" use="required" />
                <attribute name="operatorname" >
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Velcom"></enumeration>
                        <enumeration value="life"></enumeration>
                        <enumeration value="MTS"></enumeration>
                    </restriction>
                </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="callprices">
        <sequence>
            <element name="innet" type="tns:price" />
            <element name="outnet" type="tns:price" />
            <element name="landline" type="tns:price" />
        </sequence>
    </complexType>
    <complexType name="parameters">
        <sequence>
            <element name="favourites">
                <simpleType>
                    <restriction base="nonNegativeInteger">
                        <maxExclusive value="6"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="tarification">
            <simpleType>
                <restriction base="string">
                    <enumeration value="minute"></enumeration>
                    <enumeration value="second"></enumeration>
                </restriction>
            </simpleType>
            </element>
            <element name="payment" type="nonNegativeInteger" />
        </sequence>
    </complexType>
    <simpleType name="tariffName">
        <restriction base="ID">
           <pattern value="([A-Za-z]+)[0-9]?"/>
                </restriction>
            </simpleType>
    <simpleType name="price">
        <restriction base="nonNegativeInteger">
            <maxExclusive value="2000"/>
        </restriction>
    </simpleType>
</schema>

=== vika95viktoria/EpamCourses/epamTask5/out/artifacts/epamTask5_war_exploded/WEB-INF/classes/data/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/tariffs"
          xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">
    <tariff name = "Business" operatorname= "Velcom">
        <payroll>69900</payroll>
        <callprices>
            <innet>500</innet>
            <outnet>100</outnet>
            <landline>50</landline>
        </callprices>
        <sms>500</sms>
        <parameters>
            <favourites>0</favourites>
            <tarification>minute</tarification>
            <payment>50000</payment>
        </parameters>
    </tariff>
    <tariff name = "BusinessPro" operatorname= "Velcom">
        <payroll>69900</payroll>
        <callprices>
            <innet>109</innet>
            <outnet>685</outnet>
            <landline>685</landline>
        </callprices>
        <sms>350</sms>
        <parameters>
            <favourites>0</favourites>
            <tarification>minute</tarification>
            <payment>10000</payment>
        </parameters>
    </tariff>
    <tariff name = "BusinessClass">
        <payroll>890000</payroll>
        <callprices>
            <innet>0</innet>
            <outnet>599</outnet>
            <landline>599</landline>
        </callprices>
        <sms>350</sms>
        <parameters>
            <favourites>0</favourites>
            <tarification>minute</tarification>
            <payment>890000</payment>
        </parameters>
    </tariff>
    <tariff name = "SummerCalls" operatorname= "Velcom">
        <payroll>30000</payroll>
        <callprices>
            <innet>425</innet>
            <outnet>1490</outnet>
            <landline>1490</landline>
        </callprices>
        <sms>350</sms>
        <parameters>
            <favourites>5</favourites>
            <tarification>minute</tarification>
            <payment>10000</payment>
        </parameters>
    </tariff>
    <tariff name = "EverybodyTalks">
        <payroll>70000</payroll>
        <callprices>
            <innet>450</innet>
            <outnet>450</outnet>
            <landline>450</landline>
        </callprices>
        <sms>350</sms>
        <parameters>
            <favourites>5</favourites>
            <tarification>minute</tarification>
            <payment>10000</payment>
        </parameters>
    </tariff>
    <tariff name = "Smart1" operatorname= "Velcom">
        <payroll>120000</payroll>
        <callprices>
            <innet>199</innet>
            <outnet>975</outnet>
            <landline>975</landline>
        </callprices>
        <sms>350</sms>
        <parameters>
            <favourites>5</favourites>
            <tarification>minute</tarification>
            <payment>10000</payment>
        </parameters>
    </tariff>
    <tariff name = "Shoes" operatorname= "Velcom">
        <payroll>85000</payroll>
        <callprices>
            <innet>425</innet>
            <outnet>1500</outnet>
            <landline>1500</landline>
        </callprices>
        <sms>350</sms>
        <parameters>
            <favourites>5</favourites>
            <tarification>second</tarification>
            <payment>10000</payment>
        </parameters>
    </tariff>
    <tariff name = "Excellent" operatorname= "MTS">
        <payroll>70000</payroll>
        <callprices>
            <innet>350</innet>
            <outnet>350</outnet>
            <landline>350</landline>
        </callprices>
        <sms>250</sms>
        <parameters>
            <favourites>0</favourites>
            <tarification>minute</tarification>
            <payment>30000</payment>
        </parameters>
    </tariff>
    <tariff name = "Talk" operatorname= "MTS">
        <payroll>40000</payroll>
        <callprices>
            <innet>400</innet>
            <outnet>850</outnet>
            <landline>850</landline>
        </callprices>
        <sms>380</sms>
        <parameters>
            <favourites>2</favourites>
            <tarification>second</tarification>
            <payment>30000</payment>
        </parameters>
    </tariff>
    <tariff name = "EasyToSay" operatorname= "MTS">
        <payroll>3000</payroll>
        <callprices>
            <innet>550</innet>
            <outnet>1000</outnet>
            <landline>1000</landline>
        </callprices>
        <sms>250</sms>
        <parameters>
            <favourites>3</favourites>
            <tarification>second</tarification>
            <payment>30000</payment>
        </parameters>
    </tariff>
    <tariff name = "Ultra" operatorname= "MTS">
        <payroll>420000</payroll>
        <callprices>
            <innet>0</innet>
            <outnet>0</outnet>
            <landline>0</landline>
        </callprices>
        <sms>260</sms>
        <parameters>
            <favourites>0</favourites>
            <tarification>second</tarification>
            <payment>420000</payment>
        </parameters>
    </tariff>
    <tariff name = "MtsSmart" operatorname= "MTS">
        <payroll>110000</payroll>
        <callprices>
            <innet>59</innet>
            <outnet>500</outnet>
            <landline>500</landline>
        </callprices>
        <sms>400</sms>
        <parameters>
            <favourites>0</favourites>
            <tarification>minute</tarification>
            <payment>30000</payment>
        </parameters>
    </tariff>
    <tariff name = "Start" operatorname= "life">
        <payroll>0</payroll>
        <callprices>
            <innet>390</innet>
            <outnet>390</outnet>
            <landline>390</landline>
        </callprices>
        <sms>300</sms>
        <parameters>
            <favourites>4</favourites>
            <tarification>minute</tarification>
            <payment>0</payment>
        </parameters>
    </tariff>
    <tariff name = "XS" operatorname= "life">
        <payroll>30000</payroll>
        <callprices>
            <innet>0</innet>
            <outnet>540</outnet>
            <landline>540</landline>
        </callprices>
        <sms>300</sms>
        <parameters>
            <favourites>0</favourites>
            <tarification>minute</tarification>
            <payment>30000</payment>
        </parameters>
    </tariff>
    <tariff name = "L" operatorname= "life">
        <payroll>100000</payroll>
        <callprices>
            <innet>0</innet>
            <outnet>0</outnet>
            <landline>0</landline>
        </callprices>
        <sms>300</sms>
        <parameters>
            <favourites>2</favourites>
            <tarification>minute</tarification>
            <payment>10000</payment>
        </parameters>
    </tariff>
</Tariffs>
